package com.szuli.austro_download.briefing;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.apache.commons.io.FileUtils;

public class HeaderText extends TextBriefing {

	public static final String NAME = "header";
	
	
	public HeaderText() throws Exception {
		setName(NAME);
		createHeaderText();
	}

	
	private void createHeaderText() throws IOException {
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH-mm-ss");
		String timeStamp = format.format(new Date(System.currentTimeMillis()));
		File headerFile = File.createTempFile("austro_briefing_", "_header.txt");
		String content = "\n==============================================================================\n";
		content += "This file was generated by the \"Weather Briefing\" App. \n";
		content += "Creation date: " + timeStamp + "\n";
		content += "See https://github.com/szulman/weather_briefing for furhter details\n\n";
		content += "==============================================================================";
		FileUtils.write(headerFile, content, Charset.defaultCharset());
		headerFile.deleteOnExit();
		setBriefingFile(headerFile);
	}
}
